import {
  Shield,
  ShieldCheck,
  Leaf,
  Feather,
  Recycle,
  Sprout,
  Scale,
  Droplets,
  Sun,
  Wind,
  Check,
  CheckCircle2,
  ShoppingBag,
  Gift,
  Building2,
  GraduationCap,
  Globe,
  Megaphone,
  Wheat,
  Package,
  PackageOpen,
  HeartPulse,
  Home,
  PartyPopper,
  Factory,
  Footprints,
  Car,
  FlaskConical,
  Flame,
  Wrench,
  Cog,
  Construction,
  HardHat,
  Truck,
  Link2,
  Palette,
  Printer,
  Pencil,
  Briefcase,
  Ruler,
  Armchair,
  Luggage,
  Plane,
  Warehouse,
  Layers,
  Mountain,
  Tractor,
  Sparkles,
  ClipboardList,
  Send,
  Download,
  Award,
  Handshake,
  MapPin,
  Calendar,
  Gem,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  shield: Shield,
  shieldCheck: ShieldCheck,
  leaf: Leaf,
  feather: Feather,
  recycle: Recycle,
  sprout: Sprout,
  scale: Scale,
  droplet: Droplets,
  sun: Sun,
  wind: Wind,
  check: Check,
  shoppingBag: ShoppingBag,
  gift: Gift,
  building: Building2,
  graduation: GraduationCap,
  globe: Globe,
  megaphone: Megaphone,
  wheat: Wheat,
  package: Package,
  heart: HeartPulse,
  home: Home,
  party: PartyPopper,
  factory: Factory,
  shoe: Footprints,
  car: Car,
  flask: FlaskConical,
  flame: Flame,
  wrench: Wrench,
  cog: Cog,
  construction: Construction,
  hardhat: HardHat,
  truck: Truck,
  link: Link2,
  palette: Palette,
  printer: Printer,
  pencil: Pencil,
  bag: Briefcase,
  ruler: Ruler,
  chair: Armchair,
  luggage: Luggage,
  plane: Plane,
  warehouse: Warehouse,
  layers: Layers,
  mountain: Mountain,
  tractor: Tractor,
  sparkles: Sparkles,
  clipboard: ClipboardList,
  packageOpen: PackageOpen,
  send: Send,
  download: Download,
  award: Award,
  handshake: Handshake,
  mapPin: MapPin,
  calendar: Calendar,
  gem: Gem,
  checkCircle: CheckCircle2,
};

interface ProductIconProps {
  name: string;
  size?: number;
  strokeWidth?: number;
  className?: string;
}

export function ProductIcon({ name, size = 22, strokeWidth = 1.6, className }: ProductIconProps) {
  const Icon = iconMap[name] ?? Sparkles;
  return <Icon size={size} strokeWidth={strokeWidth} className={className} aria-hidden="true" />;
}
